TelescopeResultsFunction xxx links to Function
TelescopeResultsField xxx links to Function
TelescopeResultsConstant xxx links to Constant
TelescopeResultsClass xxx links to Function
TelescopePreviewMessageFillchar xxx links to TelescopePreviewMessage
TelescopePreviewMessage xxx links to TelescopePreviewNormal
TelescopePreviewNormal xxx links to TelescopeNormal
TelescopePreviewDate xxx links to Directory
TelescopePreviewGroup xxx links to Constant
TelescopePreviewUser xxx links to Constant
TelescopePreviewSize xxx links to String
TelescopePreviewSticky xxx links to Keyword
TelescopePreviewHyphen xxx links to NonText
TelescopePreviewExecute xxx links to String
TelescopePreviewWrite xxx links to Statement
TelescopePreviewRead xxx links to Constant
TelescopePreviewSocket xxx links to Statement
TelescopePreviewLink xxx links to Special
TelescopePreviewBlock xxx links to Constant
TelescopePreviewDirectory xxx links to Directory
TelescopePreviewCharDev xxx links to Constant
TelescopePreviewPipe xxx links to Constant
TelescopePreviewMatch xxx links to Search
TelescopePreviewLine xxx links to Visual
TelescopePromptPrefix xxx links to Identifier
TelescopeMatching xxx links to Special
TelescopePromptCounter xxx links to NonText
TelescopePreviewTitle xxx links to TelescopeTitle
TelescopeTitle xxx links to TelescopeBorder
TelescopeBorder xxx links to TelescopeNormal
TelescopeResultsTitle xxx links to TelescopeTitle
TelescopePromptTitle xxx links to TelescopeTitle
TelescopeNormal xxx links to Normal
TelescopePreviewBorder xxx links to TelescopeBorder
TelescopeResultsBorder xxx links to TelescopeBorder
TelescopePromptBorder xxx links to TelescopeBorder
TelescopeResultsNormal xxx links to TelescopeNormal
TelescopePromptNormal xxx links to TelescopeNormal
TelescopeMultiIcon xxx links to Identifier
TelescopeMultiSelection xxx links to Type
TelescopeSelectionCaret xxx links to TelescopeSelection
TelescopeSelection xxx links to Visual
TelescopeResultsDiffAdd xxx links to DiffAdd
TelescopeResultsDiffChange xxx links to DiffChange
TelescopeResultsSpecialComment xxx links to SpecialComment
TelescopeResultsDiffUntracked xxx links to NonText
TelescopeResultsDiffDelete xxx links to DiffDelete
TelescopeResultsNumber xxx links to Number
TelescopeResultsIdentifier xxx links to Identifier
TelescopeResultsLineNr xxx links to LineNr
TelescopeResultsVariable xxx links to SpecialChar
TelescopeResultsComment xxx links to Comment
TelescopeResultsStruct xxx links to Struct
TelescopeResultsOperator xxx links to Operator
TelescopeResultsMethod xxx links to Method
