local base = require'midnightcrawler.base'
local extra = require'midnightcrawler.extra'

return {
	Normal = { fg = base.fg, bg = 'NONE' },
	NormalFloat = { bg = extra.safari_grey },
	FloatBorder = {  },
	FloatTitle = { fg = base.fg },
	ColorColumn = { bg = extra.panel_bg_inactive },
	Cursor = { fg = base.bg, bg = base.fg },
	CursorColumn = { bg = extra.panel_bg_inactive },
	CursorLine = { bg = extra.cursor_line },
	CursorLineNr = { fg = extra.accent, bg = 'NONE' },
	LineNr = { bg = 'NONE', fg = base.fg },
	Directory = { fg = extra.func },
	ErrorMsg = { fg = extra.error },
	WinSeparator = { fg = base.bg, bg = base.bg },
	Folded = { fg = base.fg_idle, bg = extra.fold_bg },
	FoldColumn = { bg = base.bg },
	SignColumn = { bg = base.bg },
	MatchParen = { sp = extra.func, underline = true },
	ModeMsg = { fg = extra.string },
	MoreMsg = { fg = extra.string },
	NonText = { fg = base.fg },
	Pmenu = { fg = base.fg, bg = extra.selection_inactive },
	PmenuSel = { fg = extra.green, bg = extra.cursor_line },
	Question = { fg = extra.string },
	Search = { fg = base.bg, bg = extra.green },
	CurSearch = { fg = base.bg, bg = extra.golden	},
	IncSearch = { fg = base.bg, bg = extra.golden },
	SpecialKey = { fg = extra.selection_inactive },
	SpellCap = { sp = extra.tag, undercurl = true },
	SpellLocal = { sp = extra.keyword, undercurl = true },
	SpellBad = { sp = extra.error, undercurl = true },
	SpellRare = { sp = extra.regexp, undercurl = true },
	StatusLine = { fg = base.fg, bg = extra.panel_bg_inactive },
	StatusLineNC = { fg = base.fg, bg = extra.panel_bg_inactive },
	WildMenu = { fg = base.bg, bg = extra.golden },
	TabLine = { fg = base.fg, bg = extra.panel_bg_inactive },
	TabLineFill = { fg = base.fg, bg = extra.panel_bg_inactive },
	TabLineSel = { fg = base.bg, bg = extra.golden },
	Title = { fg = extra.keyword },
	Visual = { bg = extra.golden, fg = base.bg },
	WarningMsg = { fg = extra.warning },
	Comment = { fg = extra.comment, italic = true },
	Constant = { fg = extra.constant },
	String = { fg = extra.string },
	Identifier = { fg = extra.type },
	Function = { fg = extra.func },
	Statement = { fg = extra.keyword },
	Operator = { fg = extra.operator },
	Exception = { fg = extra.markup },
	PreProc = { fg = extra.accent },
	Type = { fg = extra.type },
	Structure = { fg = extra.special },
	Special = { fg = extra.accent },
	Delimiter = { fg = extra.special },
	Underlined = { sp = extra.tag, underline = true },
	Ignore = { fg = base.fg },
	Error = { fg = extra.white_smoke, bg = extra.error },
	Todo = { fg = extra.todo },
	qfLineNr = { fg = extra.keyword },
	qfError = { fg = extra.error },
	Conceal = { fg = extra.comment },
	CursorLineConceal = { fg = base.fg, bg = extra.panel_bg_inactive },
	DiffAdd = { bg = extra.vcs_added_bg },
	DiffAdded = { fg = extra.vcs_added },
	DiffDelete = { bg = extra.vcs_removed_bg },
	DiffRemoved = { fg = extra.vcs_removed },
	DiffText = { bg = extra.gutter_normal },
	DiffChange = { bg = extra.selection_inactive },
	DiagnosticError = { fg = extra.error },
	DiagnosticWarn = { fg = extra.keyword },
	DiagnosticInfo = { fg = extra.tag },
	DiagnosticHint = { fg = extra.regexp },
	DiagnosticUnderlineError = { sp = extra.error, undercurl = true },
	DiagnosticUnderlineWarn = { sp = extra.keyword, undercurl = true },
	DiagnosticUnderlineInfo = { sp = extra.tag, undercurl = true },
	DiagnosticUnderlineHint = { sp = extra.regexp, undercurl = true },
	GitSignsAddLn = { fg = extra.vcs_added },
	GitSignsDeleteLn = { fg = extra.vcs_removed },
	GitSignsChange = { fg = extra.vcs_modified },
	CursorWord = { bg = extra.selection_inactive },
	CursorWord0 = { bg = extra.selection_inactive },
	CursorWord1 = { bg = extra.selection_inactive },
	LspSignatureActiveParameter = { italic = true },
	diffFile = { link = 'Statement' },
	gitDiff = { fg = extra.white_smoke },
}
